spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
paypal:
  clientId=${PAYPAL_ID}
  clientSecret=${PAYPAL_SECRET}
  currency-code=${PAYPAL_CURRENCY_CODE}